### ISSUE TITLE
Request for Assistance with Metal Support in Flutter FFI-Plugin macOS Integration of Whisper.cpp

### ISSUE THREAD

**Issue by jianhuihi** [Telosnex/fllama#1]
I am currently working on integrating whisper.cpp into a Flutter FFI-plugin for macOS and am encountering issues with supporting Metal on macOS systems.

The main error message is as follows:

```
ggml_metal_init: allocating
ggml_metal_init: found device: Intel(R) Iris(TM) Plus Graphics
ggml_metal_init: picking default device: Intel(R) Iris(TM) Plus Graphics
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: error: could not use bundle path to find ggml-metal.metal, falling back to trying cwd
ggml_metal_init: loading 'ggml-metal.metal'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ggml-metal.metal” couldn’t be opened because there is no such file." UserInfo={NSFilePath=ggml-metal.metal, NSUnderlyingError=0x7f7cdf00a030 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
whisper_backend_init: ggml_backend_metal_init() failed
whisper_model_load: CPU total size = 147.46 MB (1 buffers)
whisper_model_load: model size = 147.37 MB
whisper_backend_init: using Metal backend
```

Based on Google tests, I see that integrating llama.cpp can address this issue, and I am curious about which specific part of the code affects the loading of 'ggml-metal.metal'.

I have also modified the .podspec file as follows:

```
s.source_files     = 'Classes/**/*', '${PODS_TARGET_SRCROOT}/../src/whisper.cpp/ggml-metal.m'
s.frameworks = 'Foundation', 'Metal', 'MetalKit'
s.script_phases = [
  {
    :name => 'Build Metal Library',
    :input_files => ["${PODS_TARGET_SRCROOT}/../src/whisper.cpp/ggml-metal.metal"],
    :output_files => ["${METAL_LIBRARY_OUTPUT_DIR}/default.metallib"],
    :execution_position => :after_compile,
    :script => <<-SCRIPT
set -e
set -u
set -o pipefail
echo "METAL_LIBRARY_OUTPUT_DIR is set to ${METAL_LIBRARY_OUTPUT_DIR}"
cd "${PODS_TARGET_SRCROOT}/../src/whisper.cpp"
xcrun metal -target "air64-${LLVM_TARGET_TRIPLE_VENDOR}-${LLVM_TARGET_TRIPLE_OS_VERSION}${LLVM_TARGET_TRIPLE_SUFFIX:-\"\"}" -ffast-math -std=ios-metal2.3 -o "${METAL_LIBRARY_OUTPUT_DIR}/default.metallib" *.metal
SCRIPT
  }
]
```

However, this has not yielded the expected results. I am seeking assistance and guidance in resolving this issue.

**Comment by jpohhhh** [comment]
Good question, please let me know how if it works for you, I just completed Whisper integration in FONNX, but I think llama.cpp will be faster:

There's two stages, #1 is easier, #2 is more complete:
1. Set the GGML_METAL_PATH_RESOURCES environment variable to a path in the package for ggml-metal.metal, i.e. the uncompiled source from the llama.cpp repo. You also have to add ggml-metal.metal to a Copy Bundle Resources in the Xcode build settings.

2. It looks like you did it right...except, I believe a fundamental limitation of CocoaPods is you cannot use files in a parent directory, i.e. it will not work correctly with paths containing ".." in them. 

If I remember right, that's why I stored 3 copies of the llama.cpp source code in the repo. I spent a few days trying to figure it out and eventually confirming the ".." in a path caused issues in any CocoaPod.

So for #2 I would copy the llama.cpp source to a directory next to the .podspec, for both iOS and macOS. Then I think the rest will work. If it does not, then, I would checking the example .xcodeproj and see what the build steps are in it, maybe I had to manually add one like Copy Bundle Resources in #1.

**Comment by jpohhhh** [comment]
Closing for tidiness, feel free to follow up and reopen

**Comment by jianhuihi** [comment]
I tried the solution you provided, and it works very well. Thank you.
